### ISSUE TITLE
Docker desktop images are 2+ months old

### ISSUE THREAD

**Issue by nbbrooks** [osrf/infrastructure#9] opened 2021-09-03 15:01 UTC
## Problem description

I don't know if this is the correct place to discuss this but did not find answers elsewhere. Currently all of the [ros-DISTRO-desktop docker images](https://hub.docker.com/r/osrf/ros/tags/?page=1&ordering=last_updated&name=desktop) are 2+ months old. Are these no longer being maintained? I enjoyed using them in my developer environment.

**Comment by sloretz** [comment] 2021-09-03 16:58
Thanks for the report! This is a duplicate of this issue: https://github.com/osrf/docker_images/issues/112

In short they get updated when the Ubuntu base image updates. There's no button we can click on dockerhub to clear the cache and rebuild them, and it's not as simple as adding a line in the Dockerfile to break the cache because the change needs to be accepted by the upstream Docker Library maintainers.

**Closed as completed by sloretz** 2021-09-03 16:58 UTC
